// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Audit_Log", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AUDIT_LOG", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.ToTable("EVENT", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EventDate = new DateTime(2026, 6, 1, 21, 24, 15, 972, DateTimeKind.Local).AddTicks(1699),
                            Name = "Gran evento",
                            Status = "Activo",
                            Venue = "Estadio A"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReservedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SeatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SeatId");

                    b.HasIndex("UserId");

                    b.ToTable("RESERVATION", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Seat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("RowIdentifier")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("integer");

                    b.Property<int>("SectorId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SectorId");

                    b.ToTable("SEAT", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000001"),
                            RowIdentifier = "Sector 1",
                            SeatNumber = 1,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000002"),
                            RowIdentifier = "Sector 1",
                            SeatNumber = 2,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000003"),
                            RowIdentifier = "Sector 1",
                            SeatNumber = 3,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000004"),
                            RowIdentifier = "Sector 1",
                            SeatNumber = 4,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000005"),
                            RowIdentifier = "Sector 1",
                            SeatNumber = 5,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000006"),
                            RowIdentifier = "Sector 1",
                            SeatNumber = 6,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000007"),
                            RowIdentifier = "Sector 1",
                            SeatNumber = 7,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000008"),
                            RowIdentifier = "Sector 1",
                            SeatNumber = 8,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000009"),
                            RowIdentifier = "Sector 1",
                            SeatNumber = 9,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000010"),
                            RowIdentifier = "Sector 1",
                            SeatNumber = 10,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000011"),
                            RowIdentifier = "Sector 1",
                            SeatNumber = 11,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000012"),
                            RowIdentifier = "Sector 1",
                            SeatNumber = 12,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000013"),
                            RowIdentifier = "Sector 1",
                            SeatNumber = 13,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000014"),
                            RowIdentifier = "Sector 1",
                            SeatNumber = 14,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000015"),
                            RowIdentifier = "Sector 1",
                            SeatNumber = 15,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000016"),
                            RowIdentifier = "Sector 1",
                            SeatNumber = 16,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000017"),
                            RowIdentifier = "Sector 1",
                            SeatNumber = 17,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000018"),
                            RowIdentifier = "Sector 1",
                            SeatNumber = 18,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000019"),
                            RowIdentifier = "Sector 1",
                            SeatNumber = 19,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000020"),
                            RowIdentifier = "Sector 1",
                            SeatNumber = 20,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000021"),
                            RowIdentifier = "Sector 1",
                            SeatNumber = 21,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000022"),
                            RowIdentifier = "Sector 1",
                            SeatNumber = 22,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000023"),
                            RowIdentifier = "Sector 1",
                            SeatNumber = 23,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000024"),
                            RowIdentifier = "Sector 1",
                            SeatNumber = 24,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000025"),
                            RowIdentifier = "Sector 1",
                            SeatNumber = 25,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000026"),
                            RowIdentifier = "Sector 1",
                            SeatNumber = 26,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000027"),
                            RowIdentifier = "Sector 1",
                            SeatNumber = 27,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000028"),
                            RowIdentifier = "Sector 1",
                            SeatNumber = 28,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000029"),
                            RowIdentifier = "Sector 1",
                            SeatNumber = 29,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000030"),
                            RowIdentifier = "Sector 1",
                            SeatNumber = 30,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000031"),
                            RowIdentifier = "Sector 1",
                            SeatNumber = 31,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000032"),
                            RowIdentifier = "Sector 1",
                            SeatNumber = 32,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000033"),
                            RowIdentifier = "Sector 1",
                            SeatNumber = 33,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000034"),
                            RowIdentifier = "Sector 1",
                            SeatNumber = 34,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000035"),
                            RowIdentifier = "Sector 1",
                            SeatNumber = 35,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000036"),
                            RowIdentifier = "Sector 1",
                            SeatNumber = 36,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000037"),
                            RowIdentifier = "Sector 1",
                            SeatNumber = 37,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000038"),
                            RowIdentifier = "Sector 1",
                            SeatNumber = 38,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000039"),
                            RowIdentifier = "Sector 1",
                            SeatNumber = 39,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000040"),
                            RowIdentifier = "Sector 1",
                            SeatNumber = 40,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000041"),
                            RowIdentifier = "Sector 1",
                            SeatNumber = 41,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000042"),
                            RowIdentifier = "Sector 1",
                            SeatNumber = 42,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000043"),
                            RowIdentifier = "Sector 1",
                            SeatNumber = 43,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000044"),
                            RowIdentifier = "Sector 1",
                            SeatNumber = 44,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000045"),
                            RowIdentifier = "Sector 1",
                            SeatNumber = 45,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000046"),
                            RowIdentifier = "Sector 1",
                            SeatNumber = 46,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000047"),
                            RowIdentifier = "Sector 1",
                            SeatNumber = 47,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000048"),
                            RowIdentifier = "Sector 1",
                            SeatNumber = 48,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000049"),
                            RowIdentifier = "Sector 1",
                            SeatNumber = 49,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000050"),
                            RowIdentifier = "Sector 1",
                            SeatNumber = 50,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000001"),
                            RowIdentifier = "Sector 2",
                            SeatNumber = 1,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000002"),
                            RowIdentifier = "Sector 2",
                            SeatNumber = 2,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000003"),
                            RowIdentifier = "Sector 2",
                            SeatNumber = 3,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000004"),
                            RowIdentifier = "Sector 2",
                            SeatNumber = 4,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000005"),
                            RowIdentifier = "Sector 2",
                            SeatNumber = 5,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000006"),
                            RowIdentifier = "Sector 2",
                            SeatNumber = 6,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000007"),
                            RowIdentifier = "Sector 2",
                            SeatNumber = 7,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000008"),
                            RowIdentifier = "Sector 2",
                            SeatNumber = 8,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000009"),
                            RowIdentifier = "Sector 2",
                            SeatNumber = 9,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000010"),
                            RowIdentifier = "Sector 2",
                            SeatNumber = 10,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000011"),
                            RowIdentifier = "Sector 2",
                            SeatNumber = 11,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000012"),
                            RowIdentifier = "Sector 2",
                            SeatNumber = 12,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000013"),
                            RowIdentifier = "Sector 2",
                            SeatNumber = 13,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000014"),
                            RowIdentifier = "Sector 2",
                            SeatNumber = 14,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000015"),
                            RowIdentifier = "Sector 2",
                            SeatNumber = 15,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000016"),
                            RowIdentifier = "Sector 2",
                            SeatNumber = 16,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000017"),
                            RowIdentifier = "Sector 2",
                            SeatNumber = 17,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000018"),
                            RowIdentifier = "Sector 2",
                            SeatNumber = 18,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000019"),
                            RowIdentifier = "Sector 2",
                            SeatNumber = 19,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000020"),
                            RowIdentifier = "Sector 2",
                            SeatNumber = 20,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000021"),
                            RowIdentifier = "Sector 2",
                            SeatNumber = 21,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000022"),
                            RowIdentifier = "Sector 2",
                            SeatNumber = 22,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000023"),
                            RowIdentifier = "Sector 2",
                            SeatNumber = 23,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000024"),
                            RowIdentifier = "Sector 2",
                            SeatNumber = 24,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000025"),
                            RowIdentifier = "Sector 2",
                            SeatNumber = 25,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000026"),
                            RowIdentifier = "Sector 2",
                            SeatNumber = 26,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000027"),
                            RowIdentifier = "Sector 2",
                            SeatNumber = 27,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000028"),
                            RowIdentifier = "Sector 2",
                            SeatNumber = 28,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000029"),
                            RowIdentifier = "Sector 2",
                            SeatNumber = 29,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000030"),
                            RowIdentifier = "Sector 2",
                            SeatNumber = 30,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000031"),
                            RowIdentifier = "Sector 2",
                            SeatNumber = 31,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000032"),
                            RowIdentifier = "Sector 2",
                            SeatNumber = 32,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000033"),
                            RowIdentifier = "Sector 2",
                            SeatNumber = 33,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000034"),
                            RowIdentifier = "Sector 2",
                            SeatNumber = 34,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000035"),
                            RowIdentifier = "Sector 2",
                            SeatNumber = 35,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000036"),
                            RowIdentifier = "Sector 2",
                            SeatNumber = 36,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000037"),
                            RowIdentifier = "Sector 2",
                            SeatNumber = 37,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000038"),
                            RowIdentifier = "Sector 2",
                            SeatNumber = 38,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000039"),
                            RowIdentifier = "Sector 2",
                            SeatNumber = 39,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000040"),
                            RowIdentifier = "Sector 2",
                            SeatNumber = 40,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000041"),
                            RowIdentifier = "Sector 2",
                            SeatNumber = 41,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000042"),
                            RowIdentifier = "Sector 2",
                            SeatNumber = 42,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000043"),
                            RowIdentifier = "Sector 2",
                            SeatNumber = 43,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000044"),
                            RowIdentifier = "Sector 2",
                            SeatNumber = 44,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000045"),
                            RowIdentifier = "Sector 2",
                            SeatNumber = 45,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000046"),
                            RowIdentifier = "Sector 2",
                            SeatNumber = 46,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000047"),
                            RowIdentifier = "Sector 2",
                            SeatNumber = 47,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000048"),
                            RowIdentifier = "Sector 2",
                            SeatNumber = 48,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000049"),
                            RowIdentifier = "Sector 2",
                            SeatNumber = 49,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000050"),
                            RowIdentifier = "Sector 2",
                            SeatNumber = 50,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        });
                });

            modelBuilder.Entity("Domain.Entities.Sector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("SECTOR", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 50,
                            EventId = 1,
                            Name = "Sector A",
                            Price = 2000m
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 50,
                            EventId = 1,
                            Name = "Sector B",
                            Price = 2500m
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("USER", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Proyecto2026@gmail.com",
                            Name = "Proyecto",
                            PasswordHash = "$2a$11$GMm86fM10GrCosygz2qqW.lxYCcxG4VUkvLyp4Ei58IhCTSDA/iIG"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Audit_Log", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Reservation", b =>
                {
                    b.HasOne("Domain.Entities.Seat", "Seat")
                        .WithMany("Reservations")
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Seat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Seat", b =>
                {
                    b.HasOne("Domain.Entities.Sector", "Sector")
                        .WithMany("Seats")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("Domain.Entities.Sector", b =>
                {
                    b.HasOne("Domain.Entities.Event", "Event")
                        .WithMany("Sectors")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Domain.Entities.Event", b =>
                {
                    b.Navigation("Sectors");
                });

            modelBuilder.Entity("Domain.Entities.Seat", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("Domain.Entities.Sector", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
